export const dashboardCopy = {
  en: {
    availability: "Availability",
    setup: "Booking style",
    services: "Services",
    tables: "Tables",
    rooms: "Rooms",
    title: "Your week, at a glance",
    intro: "Choose when people can book with you.",
    choose: "What do people book?",
    chooseHint:
      "Start with the way your business works. You can change this later.",
    appointments: "Appointments",
    appointmentsHint:
      "Your time, one client at a time. For hairdressers, tattoo artists and independent professionals.",
    tablesHint:
      "A table for their group. Give each table a name, a size and its own hours.",
    roomsHint:
      "A space of their own. Manage separate hours for studios, practice rooms and other spaces.",
    chooseAction: "Use this style",
    saved: "Saved",
    saving: "Saving…",
    error: "We couldn't save your changes. Please try again.",
    loadError: "We couldn't load this calendar.",
    retry: "Try again",
    loading: "Loading calendar…",
    myHours: "My availability",
    editHours: "Edit hours",
    noHours: "No hours this week",
    noHoursHint:
      "Add the times you're available. You can repeat them over several weeks.",
    setHours: "Set available hours",
    week: "This week",
    previous: "Previous week",
    next: "Next week",
    unavailableDay: "Unavailable",
    appointmentsNote:
      "One appointment at a time. Add services if you want clients to choose what they come in for.",
    tablesNote:
      "Each table takes one group at a time. Capacity is the maximum number of guests at that table.",
    roomsNote:
      "Each room has its own calendar. Different rooms can be available at the same time.",
    servicesHint:
      "Optional. Name your services and set their duration. Only offer a first consultation? Add just that.",
    tableListHint:
      "Add each physical table once, with the number of people it seats.",
    roomListHint: "Add each space once. Give it a name clients will recognize.",
    addService: "Add service",
    addTable: "Add table",
    addRoom: "Add room",
    edit: "Edit",
    cancel: "Cancel",
    save: "Save changes",
    name: "Name",
    capacity: "Maximum people",
    duration: "Duration in minutes",
    active: "Available to book",
    paused: "Paused",
    pause: "Pause",
    resume: "Resume",
    nameService: "e.g. Haircut or first consultation",
    nameTable: "e.g. Table 1 · window",
    nameRoom: "e.g. Solo studio",
    noServices: "Keep it simple, or offer a choice",
    noServicesHint: "You can use your availability without a service list.",
    noTables: "Let's add your tables",
    noRooms: "Let's add your rooms",
    noResourcesHint: "Then set the available hours for each one.",
    people: "people",
    minutes: "min",
    current: "Current style",
    styleHint:
      "Changing style keeps all your services, tables, rooms and saved hours. They reappear when you switch back.",
    calendar: "Calendar",
    pausedHint: "This is paused. Its hours are saved for when you resume it.",
    flow: "How clients will book",
    serviceStep: "Choose a service",
    timeStep: "Choose a time",
    detailsStep: "Leave their details",
    guestsStep: "Select group size",
    roomStep: "Choose a room",
    flowHint:
      "This is your booking setup. Public booking pages are not available yet.",
    yourTime: "Your time",
    ownCalendar: "Separate calendar",
    selectResource: "Choose a calendar",
    manage: "Manage",
    hoursFor: "Hours for",
  },
  nl: {
    availability: "Beschikbaarheid",
    setup: "Boekingsvorm",
    services: "Diensten",
    tables: "Tafels",
    rooms: "Ruimtes",
    title: "Je week in één oogopslag",
    intro: "Bepaal wanneer mensen bij je kunnen boeken.",
    choose: "Wat boeken mensen bij jou?",
    chooseHint: "Kies wat bij je bedrijf past. Je kunt dit later wijzigen.",
    appointments: "Afspraken",
    appointmentsHint:
      "Jouw tijd, één klant tegelijk. Voor kappers, tattoo-artiesten en zelfstandigen.",
    tablesHint:
      "Een tafel voor hun gezelschap. Geef elke tafel een naam, capaciteit en eigen tijden.",
    roomsHint:
      "Een eigen ruimte. Beheer aparte tijden voor studio's, oefenruimtes en andere ruimtes.",
    chooseAction: "Kies deze vorm",
    saved: "Opgeslagen",
    saving: "Opslaan…",
    error: "Opslaan is niet gelukt. Probeer het opnieuw.",
    loadError: "We konden deze agenda niet laden.",
    retry: "Opnieuw proberen",
    loading: "Agenda laden…",
    myHours: "Mijn beschikbaarheid",
    editHours: "Tijden wijzigen",
    noHours: "Geen tijden deze week",
    noHoursHint:
      "Voeg de tijden toe waarop je beschikbaar bent. Je kunt ze voor meerdere weken herhalen.",
    setHours: "Beschikbaarheid instellen",
    week: "Deze week",
    previous: "Vorige week",
    next: "Volgende week",
    unavailableDay: "Niet beschikbaar",
    appointmentsNote:
      "Eén afspraak tegelijk. Voeg diensten toe als je klanten wilt laten kiezen waarvoor ze komen.",
    tablesNote:
      "Elke tafel is voor één gezelschap tegelijk. De capaciteit is het maximale aantal gasten aan die tafel.",
    roomsNote:
      "Elke ruimte heeft een eigen agenda. Verschillende ruimtes kunnen tegelijk beschikbaar zijn.",
    servicesHint:
      "Optioneel. Geef je diensten een naam en duur. Alleen een kennismaking aanbieden? Voeg alleen die toe.",
    tableListHint: "Voeg elke tafel één keer toe, met het aantal zitplaatsen.",
    roomListHint:
      "Voeg elke ruimte één keer toe. Kies een naam die klanten herkennen.",
    addService: "Dienst toevoegen",
    addTable: "Tafel toevoegen",
    addRoom: "Ruimte toevoegen",
    edit: "Wijzigen",
    cancel: "Annuleren",
    save: "Wijzigingen opslaan",
    name: "Naam",
    capacity: "Maximaal aantal personen",
    duration: "Duur in minuten",
    active: "Boekbaar",
    paused: "Gepauzeerd",
    pause: "Pauzeren",
    resume: "Hervatten",
    nameService: "Bijv. Knippen of kennismaking",
    nameTable: "Bijv. Tafel 1 · raam",
    nameRoom: "Bijv. Solostudio",
    noServices: "Houd het eenvoudig, of bied een keuze",
    noServicesHint:
      "Je kunt je beschikbaarheid zonder dienstenlijst gebruiken.",
    noTables: "Voeg je tafels toe",
    noRooms: "Voeg je ruimtes toe",
    noResourcesHint:
      "Stel daarna per tafel of ruimte de beschikbare tijden in.",
    people: "personen",
    minutes: "min",
    current: "Huidige vorm",
    styleHint:
      "Bij een andere vorm blijven al je diensten, tafels, ruimtes en tijden bewaard. Je ziet ze weer zodra je terugschakelt.",
    calendar: "Agenda",
    pausedHint: "Dit is gepauzeerd. De tijden blijven bewaard tot je hervat.",
    flow: "Hoe klanten straks boeken",
    serviceStep: "Kies een dienst",
    timeStep: "Kies een tijd",
    detailsStep: "Vul gegevens in",
    guestsStep: "Kies het aantal personen",
    roomStep: "Kies een ruimte",
    flowHint:
      "Dit is je boekingsopzet. Openbare boekingspagina's zijn nog niet beschikbaar.",
    yourTime: "Jouw tijd",
    ownCalendar: "Eigen agenda",
    selectResource: "Kies een agenda",
    manage: "Beheren",
    hoursFor: "Tijden voor",
  },
} as const;
